apiVersion: v1
kind: Service
metadata:
  name: webapp-canary-service
spec:
  selector:
    app: webapp # matches both canary and stable deployments 
  ports:
  - port: 80
    targetPort: 80
 