# Pod Disruption Budget -> Prevent too many pods down at once 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: mongodb 
spec: 
  minAvailable: 2
  selector: 
    matchLabels:
      app: mongodb
